IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DeviceWarehouse]') AND type in (N'U'))
BEGIN
    DROP TABLE [dbo].[DeviceWarehouse];
END
GO

CREATE TABLE [dbo].[DeviceWarehouse](
    [RowId] INT NOT NULL IDENTITY(1,1),
    [Key] [UNIQUEIDENTIFIER] NOT NULL DEFAULT NEWID(),
    [Name] [NVARCHAR](256) NOT NULL,
    [Model] [NVARCHAR](256) NULL,
    [SerialNumber] [NVARCHAR](512) NULL,
    [DeviceId] [NVARCHAR](512) NULL,
    [OperationSystem] [NVARCHAR](512) NULL,
    [Description] [NVARCHAR](512) NULL,
    [OwnerKey] [UNIQUEIDENTIFIER] NULL,
    [BorrowerKey] [UNIQUEIDENTIFIER] NULL,
    [CreatedStamp] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    [LastUpdatedStamp] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    [CreatedBy] [UNIQUEIDENTIFIER] NOT NULL,
    [LastUpdatedBy] [UNIQUEIDENTIFIER] NOT NULL,
    [State] [int] NOT NULL DEFAULT 0,
CONSTRAINT [PK_DeviceWarehouse_Key] PRIMARY KEY NONCLUSTERED 
(
    [Key] ASC
),
CONSTRAINT [CIX_DeviceWarehouse] UNIQUE CLUSTERED 
(
    [RowId] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);