IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DynamicFieldValue]') AND type in (N'U'))
DROP TABLE [dbo].[DynamicFieldValue]
GO

CREATE TABLE [dbo].[DynamicFieldValue](
    [RowId] INT NOT NULL IDENTITY(1,1),
    [Key] [UNIQUEIDENTIFIER] NOT NULL DEFAULT NEWID(),
    [EntityPrimaryKey] [UNIQUEIDENTIFIER] NOT NULL,
    [FieldKey] [UNIQUEIDENTIFIER] NOT NULL,
    [EntityKey] [UNIQUEIDENTIFIER] NOT NULL,
    [FieldValue] NVARCHAR(MAX) NOT NULL DEFAULT '',
    [CreatedStamp] [DATETIME] NOT NULL DEFAULT GETUTCDATE(),
    [LastUpdatedStamp] [DATETIME] NOT NULL DEFAULT GETUTCDATE(),
    [State] [int] NOT NULL DEFAULT 0,
CONSTRAINT [PK_DynamicFieldValue_Key] PRIMARY KEY NONCLUSTERED 
(
    [Key] ASC
),
CONSTRAINT [CIX_DynamicFieldValue] UNIQUE CLUSTERED 
(
    [RowId] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

GO

