IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SessionInfo]') AND type in (N'U'))
BEGIN
    DROP TABLE [dbo].[SessionInfo];
END
GO

CREATE TABLE [dbo].[SessionInfo](
    [RowId] [INT] NOT NULL IDENTITY(1,1),
    [Token] VARCHAR(512) NOT NULL DEFAULT '' UNIQUE,
    [UserKey] [UNIQUEIDENTIFIER] NOT NULL,
    [UserAgent] VARCHAR(512) NULL,
    [Platform] INT NOT NULL DEFAULT 0,
    [DeviceType] INT NOT NULL DEFAULT 0,
    [IpAddress] VARCHAR(64) NULL,
    [CreatedStamp] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    [LastUpdatedStamp] DATETIME NOT NULL DEFAULT GETUTCDATE(),
    [ExpiredStamp] DATETIME NOT NULL,
CONSTRAINT [PK_SessionInfo_Key] PRIMARY KEY NONCLUSTERED 
(
    [Token] ASC
),
CONSTRAINT [CIX_SessionInfo] UNIQUE CLUSTERED 
(
    [RowId] ASC
)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
);

GO